name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose up -d --build 
      
    - name: Restart redis-server
      run: docker exec -i backend bash -c '/etc/init.d/redis-server restart'

    - name: Run Pytest
      run: docker exec -i backend pytest -vv
